### ISSUE TITLE
Is development stopped?

### ISSUE THREAD

**Issue by CC84** [CirclonGroup/angular-tree-component#541]
Here are a lot of issues but no responses or codechanges in the last month.

Will it go on soon or is it better to search for an alternative.

**Comment by JanLoebel** [comment]
The last commit was: 3 days ago, see: 

https://github.com/500tech/angular-tree-component/commit/1ec345a2a8a39e672bac61187626b7a6ec6ab0b0

So I'm pretty sure it's still developed ;)

**Comment by erickyi2006** [comment]
@CC84 , what other alternatives are there? 
fyi, i have evaluated many tree view libs out there that support angular 4 since may last year and i am pretty happy with the version upgrades. I am rapped to see it now supports angular 5. the only choice i will move one is when the material angular finally release its implementation to the master branch and if it is better than this one. :)

**Comment by KeithGillette** [comment]
I am beginning to suspect that the project has become too much for the maintainer to support as an open source project, as:

1. There hasn't been a new release since December.
2. There are many outstanding PRs.
3. As far as I've seen, the maintainer hasn't responded in the Issues forums for months (even to @mentions offering help in PRs).
4. Recent updates to the [`README.md`](https://github.com/500tech/angular-tree-component/blob/master/README.md#support) now direct to a form the request price quotes.

I'd hate to see this project stall without active leadership, as I've been quite happy with this component, as well, and am using in extensively in my project. I haven't seen anything as full-featured, though the PrimeNG [Tree](http://primefaces.org/primeng/#/tree) and [TreeTable](http://primefaces.org/primeng/#/treetable) do look pretty good now.

**Comment by tobiasengelhardt** [comment]
Closing this because development is not stopped ;)
