### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by avs2001** [CirclonGroup/angular-tree-component#832]
Can you export as es module?

**Comment by tobiasengelhardt** [comment]
There will be an Angular 10 Version soon (2 - 3 Weeks).

**Comment by robntracts** [comment]
@tobiasengelhardt I am evaluating this package for our company. Is there a target date for Angular 10? Our app has already been updated. I can downgrade for evaluation but it will be harder to convince other devs while it doenst support 10. Thanks! Package looks awesome.

**Comment by tobiasengelhardt** [comment]
@robntracts There are currently some npm issues we are working on. As you can see in the code the Angular 9 version is ready - but not yet published because of those issues. The general roadmap is pretty much to go straight to an Angular 10 version and focus the new development there. I don't see any issues going from 9 to 10, so once those npm issues are cleared up it will only take a couple of days.
Version 9 of the angular-tree-component should be published this week. That one should not make problems in an Angular 10 app - but I have not tested this yet.

**Comment by robntracts** [comment]
We are going with this package. Just suppressed the es module warnings for now. This package is really nice.

**Comment by tobiasengelhardt** [comment]
There is now `10.0.0-beta.0` released to see if it works in your Angular 10 apps. Let us know if you tested it out. If no issues are coming in we will release `10.0.0` next week.

**Comment by grunk** [comment]
Can confirm that v9.0.3 is working fine with angular 10. Just had to update the package scope.
I had to put virtualscroll to false (was true before) in order to have my tree displayed , but unsure that this linked to this particular version or an error on my side.

**Comment by tobiasengelhardt** [comment]
`10.0.0` is now released. If there are problems please open a new issue.
