### ISSUE TITLE
@types/lodash has no exported member 'Cancelable'

### ISSUE THREAD

**Issue by Prabukmca** [CirclonGroup/angular-tree-component#861]
I have tried npm -D @types/lodash, and removed node_modules and installed again, still I'm facing this issue, unable build our application. Kindly help or provide work around.

------------------------------------------
ERROR in ../node_modules/angular-tree-component/dist/components/tree-viewport.component.d.ts:3:10 - error TS2305: Module "..../Client/***/ClientApp/node_modules/@types/lodash"' has no exported member 'Cancelable'.

3 import { Cancelable } from 'lodash';

------------------------------------

"angular-tree-component": "^8.5.6"
"lodash": "^4.17.20",
"@types/lodash": "^4.14.162",

We are using Angular 8 and the above packages, Kindly help.

**Comment by tobiasengelhardt** [comment]
@Prabukmca, sorry for the late reply. I was on vacation.
There are some other issues regarding this. Please take a look into #859 . It seems that `"@types/lodash": "4.14.160"` is working. The newer versions of types/lodash are the problem. We sadly can not just simply fix the version 8 of the tree because we don't have the ownership of that npm package.

If this does not solve your problem please write in the other issue. There you can also write if you would like a fix for version 8. But note that we can only solve this in the new npm package name and it will require changes in your code to adjust to the new package. I'm closing this here to focus all the cancelable issues in #856 .
