### ISSUE TITLE
NVD CVE-2020-8203 (BDSA-2020-1674) Issue with lodash-es 4.17.15

### ISSUE THREAD

**Issue by somuda86** [CirclonGroup/angular-tree-component#862]
Please upgrade to lodash-es 4.17.20

https://www.openhub.net/p/616506

**Comment by somuda86** [comment]
@tobiasengelhardt This is a high priority security issue. Please comment. angular tree component is using vulnerable lodash version. Thanks

**Comment by tobiasengelhardt** [comment]
@somuda86 It's sadly not an easy update. There is no lodash-es `4.17.20`, we are using the most recent version. They seem to have [issues publishing a new version](https://github.com/lodash/lodash/issues/4879). I hope they fix this soon.

**Comment by matiassantos** [comment]
What a pity., this issue will prevent the usage of this component in production environments until lodash fixes the issue. 
Do you have an estimate of the work needed to fix this project when the lodash version is updated to 4.17.20? any known breaking functionalities?

**Comment by tobiasengelhardt** [comment]
Looking at the changelog of lodash they did only bugfixes. If they finally publish `4.17.20` it should be just a simple package update.

**Comment by tobiasengelhardt** [comment]
Because there seems to be no real progress regarding the release of a new lodash version we started looking into removing lodash as a dependency. The `pr/remove-lodash` branch has lodash removed and all our build tests are passing (feel we to look, leave feedback and input). This is still a bigger change so we will do some more testing to see if it everything is working correctly. Hopefully there will be a new version released within the next two weeks.
If lodash release a new version before we are done testing there will of course be a new version with the updated lodash version asap.

**Comment by matiassantos** [comment]
Sure! i'd be glad to help

**Comment by somuda86** [comment]
4.17.20.has been released. But my 2 cents on removing that dependency

**Comment by tobiasengelhardt** [comment]
Fix is released in `10.0.2`. We will continue working on removing lodash.
